# Generated by Django 4.0.2 on 2022-04-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piercings',
            old_name='destaque_piercings',
            new_name='destaque',
        ),
        migrations.RenameField(
            model_name='tattoo',
            old_name='destaque_tattoo',
            new_name='destaque',
        ),
    ]
