# Generated by Django 4.0.2 on 2022-05-09 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_destaque_piercings_piercings_destaque_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Piercings',
        ),
        migrations.DeleteModel(
            name='Tattoo',
        ),
    ]
