# Generated by Django 4.0.2 on 2022-05-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_agenda',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
