# Generated by Django 4.0.2 on 2022-05-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_agenda_options_alter_agenda_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={},
        ),
        migrations.AlterModelTable(
            name='agenda',
            table=None,
        ),
    ]
